### PR TITLE
Add Quine example

### PR DESCRIPTION
**Pull request by Aschen**
## What does this PR do?

Adds a quine example in the README

```
$ kourou-dev sdk:execute --print-raw --code '(
  function quine() {
    const sq = String.fromCharCode(39);
    const lp = String.fromCharCode(40);
    const rp = String.fromCharCode(41);

    console.log("kourou-dev sdk:execute --print-raw --code " + sq + lp + quine.toString() + rp + lp + rp + ";" + sq)
  }
)()' > result.txt

$ cat result.txt 
kourou-dev sdk:execute --print-raw --code '(function quine() {
    const sq = String.fromCharCode(39);
    const lp = String.fromCharCode(40);
    const rp = String.fromCharCode(41);

    console.log("kourou-dev sdk:execute --print-raw --code " + sq + lp + quine.toString() + rp + lp + rp + ";" + sq)
  })();'
```

### Other Changes

 - add the `print-raw` option to print only the script output

### CODE REVIEW

**Comment by scottinet** [comment]
What's the purpose of documentation that?

**Comment by Aschen** [comment]
> What's the purpose of documentation that?

Fun?

**Comment by scottinet** [comment]
It might be, but since kourou is meant for the average user, I'm afraid that it's more confusing than anything.

**Comment by Aschen** [comment]
> It might be, but since kourou is meant for the average user, I'm afraid that it's more confusing than anything.

We already have the small paragraph about Kourou naming :sweat_smile: 

Maybe a warning saying that this is for recreational purpose only?

IMHO it is interesting to develop the IT culture of our users :smile:

**Review by xbill82 — APPROVED** [review]
😄

**Review by jenow — APPROVED** [review]

**Pull request merged**
