### PR TITLE
Allow user to select the applicationId he want to deploy

### PR DESCRIPTION
**Pull request by rolljee**
# Overview

This feature is needed for the new paas possibility of having multiple kuzzle in an env

### CODE REVIEW

**Review by Shiranuit — APPROVED** [review]

**Review by alexandrebouthinon — COMMENTED** [review]
To avoid breaking previously established CI/CD we should use `kuzzle` as the default value for this new argument

**Review by Aschen — CHANGES_REQUESTED** [review]
I agree with @alexandrebouthinon comment, default value should be `kuzzle`

**Comment by rolljee** [comment]
@Aschen @alexandrebouthinon 

This is pointless, it will not work anyway even with the default value as kuzzle.

The new process now use `_id` witch is choosen by the user, kuzzle was the property `name`.

The code does not use the property name anymore.

We will need to go through each individual CI/CD to modify it anyway.

**Review by Aschen — COMMENTED** [review]
I leave you this PR since I don't have enough knowledge to review it

**Comment by rolljee** [comment]
@Aschen I'll need you to accept the PR so i can merge it :)

**Review by Aschen — APPROVED** [review]

**Pull request merged**
